name: "Hello World Demo!!!"

on:
    push:
        branches:
            - main 
jobs:
    Hello_World:
        runs-on: ubuntu-latest
        steps:
            - name: "Hello world Steps"
              run: echo "Hello my dear friends, I'm alive!!!"
            - name: "Step NO - 2 "
              run: echo "My second command also has run!"


